-- Colorscheme generated by https://github.com/arcticlimer/djanho
vim.cmd[[highlight clear]]

local highlight = function(group, bg, fg, attr)
    fg = fg and 'guifg=' .. fg or ''
    bg = bg and 'guibg=' .. bg or ''
    attr = attr and 'gui=' .. attr or ''

    vim.api.nvim_command('highlight ' .. group .. ' '.. fg .. ' ' .. bg .. ' '.. attr)
end

local link = function(target, group)
    vim.api.nvim_command('highlight! link ' .. target .. ' '.. group)
end

local CommentGray = '#888888'
local StringTeal = '#5BD1B9'
local YellowOrange = '#FAC760'
local LightYellowOrange = '#a6c4ff'
local FunctionBlue = '#43AAF9'
local KeywordPink = '#DD4F7D'
local RegularWhite = '#EFEFEF'
local ErrorRed = '#E34234'
local Black = '#000000'
local MenuWhite = '#DCE3EA'
local VisualBGDarkBlue = '#163853'
local LineNumberGrey = '#454d54'
local AlmostBlack = '#020202'
local MiscGrey = '#75797c'
local LighterPurple = '#bf98ff'

highlight('Normal', Black, MenuWhite, nil)
highlight('Visual', VisualBGDarkBlue, nil, nil)

highlight('Comment', nil, CommentGray, nil)
link('NonText', 'Comment')

highlight('Constant', nil, RegularWhite, 'italic')
link('@parameter', 'Constant')
link('@field', 'Constant')

highlight('String', nil, StringTeal, nil)
link('Character', 'String')
link('TSCharacter', 'String')

--highlight('TSCharacter', nil, FunctionBlue, nil)
highlight('Number', nil, YellowOrange, nil)
link('Float', 'Number')
link('TSFloat', 'Number')
link('Boolean', 'Number')

highlight('Identifier', nil, RegularWhite, nil)
highlight('@variable', nil, RegularWhite, nil)
highlight('@variable.builtin', nil, KeywordPink, nil)
highlight('Function', nil, FunctionBlue, 'bold')
highlight('Statement', nil, KeywordPink, 'bold')
highlight('Conditional', nil, KeywordPink, 'bold')
link('Repeat', 'Conditional')
link('Label', 'Conditional')
link('TSLabel', 'Conditional')

highlight('@operator', nil, RegularWhite, 'bold')
highlight('Operator', nil, FunctionBlue, nil)
link('TSOperator', 'Operator')

highlight('Keyword', nil, KeywordPink, 'bold')
link('Exception', 'Keyword')

highlight('@type', nil, YellowOrange, nil)
highlight('@type.builtin', nil, KeywordPink, nil)
highlight('@constant.builtin', nil, KeywordPink, nil)
link('Type', '@type')
link('StorageClass', 'Type')
link('Structure', 'Type')
link('Typedef', 'Type')

highlight('@tag', nil, LighterPurple, nil)
highlight('@tag.delimiter', nil, RegularWhite, nil)
highlight('@tag.attribute', nil, YellowOrange, 'italic')
highlight('@constructor', nil, KeywordPink, nil)

highlight('Punctuation', nil, LightYellowOrange, nil)
link('@punctuation', 'Punctuation')

highlight('@punctuation.delimiter', nil, MenuWhite, nil)
highlight('PunctDelimiter', nil, MenuWhite, nil)
highlight('TSPunctDelimiter', nil, MenuWhite, nil)

highlight('PreProc', nil, KeywordPink, 'bold')
link('Include', 'PreProc')
link('Define', 'PreProc')
link('Macro', 'PreProc')
link('PreCondit', 'PreProc')

highlight('Error', nil, ErrorRed, nil)

highlight('StatusLine', MenuWhite, Black, nil)
highlight('WildMenu', Black, MenuWhite, nil)
highlight('Pmenu', Black, MenuWhite, nil)
highlight('PmenuSel', MenuWhite, nil, nil)
highlight('PmenuThumb', Black, MenuWhite, nil)

highlight('CursorLine', VisualBGDarkBlue, nil, nil)
highlight('ColorColumn', VisualBGDarkBlue, nil, nil)
highlight('SignColumn', Black, nil, nil)
highlight('LineNr', nil, LineNumberGrey, nil)
highlight('TabLine', AlmostBlack, MiscGrey, nil)
highlight('TabLineFill', AlmostBlack, MiscGrey, nil)

